# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NZ9zqTj0-wNyCyKCfbRf_DwnxH0KTgDL
"""

#imports
import networkx as nx


# Create graph
G = nx.Graph()

edges = [
    ("Mensah", "Freddie"),
    ("Mensah", "Ama"),
    ("Mensah", "Kojo"),
    ("Ama", "Freddie"),
    ("Kojo", "Linda")
]

G.add_edges_from(edges)


degrees = list(G.degree())
isolated = list(nx.isolates(G))

print("Number of nodes:", G.number_of_nodes())
print("Number of edges:", G.number_of_edges())
print("Degree distribution:", degrees)
print("Isolated nodes:", isolated)



# customize
nx.draw(G, node_color='lightblue', with_labels=True, node_size=2000,)

